In [1]:
!pip install flask-ngrok
!pip install google-colab
!pip install tensorflow
!pip install keras
!pip install pillow
!pip install pillow==4.1.1
%reload_ext autoreload
%autoreload

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 462 kB 24.6 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 11.3 MB 22.4 MB/s 
     |████████████████████████████████| 112 kB 48.3 MB/s 
  Created wheel for pillow: filename=Pillow-4.1.1-cp37-cp37m-linux_x86_64.whl size=1009735 sha256=7121297c47bbbf34a957bd87dc32445cd91b5e4652e25021922113a238740711
  Stored in directory: /root/.cache/pip/wheels/51/53/67/d76ff9fd54dd

In [1]:
# !pip install google-colab

from google.colab import drive
drive.mount('./drive')


Mounted at ./drive


In [2]:
cd /content/drive/MyDrive/Colab Notebooks/models 

/content/drive/MyDrive/Colab Notebooks/models


In [3]:
!pip install pyngrok==4.1.1
!ngrok authtoken 1hmRRl6ZYjxLqCode30MaVQk1kx_6DjEkRGLotgKYSGJ1zCGu 



Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for pyngrok: filename=pyngrok-4.1.1-py3-none-any.whl size=15983 sha256=012e56753aae3e6d930b53d28cd67658e55d3d28a21cf807480154e86c4d3a96
  Stored in directory: /root/.cache/pip/wheels/b1/d9/12/045a042fee3127dc40ba6f5df2798aa2df38c414bf533ca765
Successfully built pyngrok
Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml


In [4]:
import numpy as np
from flask import Flask, request, render_template
from flask import jsonify
from flask_ngrok import run_with_ngrok
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing import image
from keras.utils.data_utils import get_file


In [5]:
#!ngrok config add-authtoken 1hmRRl6ZYjxLqCode30MaVQk1kx_6DjEkRGLotgKYSGJ1zCGu

In [ ]:
app = Flask(__name__)
run_with_ngrok(app)
# model.summary()
import os
def getpredictions(filename):
    model = keras.models.load_model("my_model.h5")
  
    img_height = 120
    img_width  = 120  
    
    image_url = tf.keras.utils.get_file('Court', origin=filename )
    img1 = tf.keras.preprocessing.image.load_img(image_url, target_size=(img_height, img_width))  
    print(image_url)
    
    os.remove(image_url) # Remove the cached file
    # img1 = image.load_img(filename,target_size=(img_height, img_width))
    # img1 = image.load_img(filename,target_size=(img_height, img_width))
    
 
    Y = image.img_to_array(img1)
    
    X = np.expand_dims(Y,axis=0)
    
    val = model.predict(X)

    print(val)
    val = list(val[0])
    
    
    print(val)
    class_of_object = ['DiGeorge_Syndrome', 'Down_syndrome', 'Noonan_Syndrome', 'Normal_people', 'William_buren_syndrome']

    result = {}
    for i in range(0,len(val)):
        result[class_of_object[i]] = str(val[i])

    
    print(result)
    
    temp = max(val)
    
    max_index = val.index(temp)
    
    print(class_of_object)

    return result
    # print(f"Class={class_of_object[max_index]}, Probability={temp}")


@app.route('/')
def home():
    return jsonify({"Success":"Welcome to Diagnozifyzz API Service !"})

@app.route('/predict',methods=['POST'])
def getprediction():
  try:
    data = request.json
    print(data)
    imageUrl = data['image_url']
    print(imageUrl)
    res = getpredictions(imageUrl)
    return jsonify(
        
        {
            "success":True,
            "msg":"successfull prediction !",
            "data":res
        }
    )   
  except Exception as e:
    print(e)
    return jsonify({"success":False,"msg":"wrong formated image !","data":None},)

app.run()



 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)


 * Running on http://e870-34-150-190-114.ngrok.io
 * Traffic stats available on http://127.0.0.1:4040
{'image_url': 'https://firebasestorage.googleapis.com/v0/b/diagnozifyfirebase.appspot.com/o/images%2FUyM0BtboySM3yFitooXorLEOOUu2?alt=media&token=f755336d-ebed-40e5-9fb6-05b79ca4d53d'}
https://firebasestorage.googleapis.com/v0/b/diagnozifyfirebase.appspot.com/o/images%2FUyM0BtboySM3yFitooXorLEOOUu2?alt=media&token=f755336d-ebed-40e5-9fb6-05b79ca4d53d
24576/9123 [================================================================================] - 0s 0us/step
/root/.keras/datasets/Court


127.0.0.1 - - [29/May/2022 15:44:46] "POST /predict HTTP/1.1" 200 -


[[6.4235342e-06 1.7219705e-03 8.9364476e-06 9.9826247e-01 2.5076176e-07]]
[6.423534e-06, 0.0017219705, 8.936448e-06, 0.99826247, 2.5076176e-07]
{'DiGeorge_Syndrome': '6.423534e-06', 'Down_syndrome': '0.0017219705', 'Noonan_Syndrome': '8.936448e-06', 'Normal_people': '0.99826247', 'William_buren_syndrome': '2.5076176e-07'}
['DiGeorge_Syndrome', 'Down_syndrome', 'Noonan_Syndrome', 'Normal_people', 'William_buren_syndrome']
{'image_url': 'https://firebasestorage.googleapis.com/v0/b/diagnozifyfirebase.appspot.com/o/images%2FUyM0BtboySM3yFitooXorLEOOUu2?alt=media&token=769a6622-c623-4ae2-a0db-2c15e03a89de'}
https://firebasestorage.googleapis.com/v0/b/diagnozifyfirebase.appspot.com/o/images%2FUyM0BtboySM3yFitooXorLEOOUu2?alt=media&token=769a6622-c623-4ae2-a0db-2c15e03a89de
548864/535674 [==============================] - 0s 0us/step
/root/.keras/datasets/Court


127.0.0.1 - - [29/May/2022 15:57:06] "POST /predict HTTP/1.1" 200 -


[[3.3975995e-04 1.7480731e-02 7.2405604e-04 9.8088557e-01 5.6986266e-04]]
[0.00033975995, 0.017480731, 0.00072405604, 0.98088557, 0.00056986266]
{'DiGeorge_Syndrome': '0.00033975995', 'Down_syndrome': '0.017480731', 'Noonan_Syndrome': '0.00072405604', 'Normal_people': '0.98088557', 'William_buren_syndrome': '0.00056986266'}
['DiGeorge_Syndrome', 'Down_syndrome', 'Noonan_Syndrome', 'Normal_people', 'William_buren_syndrome']
{'image_url': 'https://firebasestorage.googleapis.com/v0/b/diagnozifyfirebase.appspot.com/o/images%2FUyM0BtboySM3yFitooXorLEOOUu2?alt=media&token=0c9f8636-ab40-4502-8667-fcb75bb0e22c'}
https://firebasestorage.googleapis.com/v0/b/diagnozifyfirebase.appspot.com/o/images%2FUyM0BtboySM3yFitooXorLEOOUu2?alt=media&token=0c9f8636-ab40-4502-8667-fcb75bb0e22c
24576/9123 [================================================================================] - 0s 0us/step
/root/.keras/datasets/Court


127.0.0.1 - - [29/May/2022 16:08:19] "POST /predict HTTP/1.1" 200 -


[[6.4235342e-06 1.7219705e-03 8.9364476e-06 9.9826247e-01 2.5076176e-07]]
[6.423534e-06, 0.0017219705, 8.936448e-06, 0.99826247, 2.5076176e-07]
{'DiGeorge_Syndrome': '6.423534e-06', 'Down_syndrome': '0.0017219705', 'Noonan_Syndrome': '8.936448e-06', 'Normal_people': '0.99826247', 'William_buren_syndrome': '2.5076176e-07'}
['DiGeorge_Syndrome', 'Down_syndrome', 'Noonan_Syndrome', 'Normal_people', 'William_buren_syndrome']
{'image_url': 'https://firebasestorage.googleapis.com/v0/b/diagnozifyfirebase.appspot.com/o/images%2FUyM0BtboySM3yFitooXorLEOOUu2?alt=media&token=58a507bd-5a79-44a1-a231-6b6237f4fb3e'}
https://firebasestorage.googleapis.com/v0/b/diagnozifyfirebase.appspot.com/o/images%2FUyM0BtboySM3yFitooXorLEOOUu2?alt=media&token=58a507bd-5a79-44a1-a231-6b6237f4fb3e
16384/6220 [===============================================================================] - 0s 0us/step
/root/.keras/datasets/Court


127.0.0.1 - - [29/May/2022 16:10:10] "POST /predict HTTP/1.1" 200 -


[[3.4208486e-03 5.3413641e-01 4.5381458e-03 4.5739347e-01 5.1111408e-04]]
[0.0034208486, 0.5341364, 0.004538146, 0.45739347, 0.0005111141]
{'DiGeorge_Syndrome': '0.0034208486', 'Down_syndrome': '0.5341364', 'Noonan_Syndrome': '0.004538146', 'Normal_people': '0.45739347', 'William_buren_syndrome': '0.0005111141'}
['DiGeorge_Syndrome', 'Down_syndrome', 'Noonan_Syndrome', 'Normal_people', 'William_buren_syndrome']
